status = [
  "cargo test",
  "cargo test (stable, i686-pc-windows-msvc, windows-latest)",
  "cargo test (stable, i686-unknown-linux-gnu, ubuntu-latest)",
  "cargo test (stable, x86_64-apple-darwin, macos-latest)",
  "cargo test (stable, x86_64-pc-windows-msvc, windows-latest)",
  "cargo test (stable, x86_64-unknown-linux-gnu, ubuntu-latest)",
  "cargo hack check --feature-powerset",
  "cargo fmt --check",
  "cargo clippy",
  "cargo audit",
  "cargo doc --cfg docsrs",
]
delete_merged_branches = true
